# Generated by Django 5.2.15 on 2026-06-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('registered_domain', models.CharField(db_index=True, max_length=255)),
                ('max_instances', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=32)),
                ('expiry_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'status'], name='licenses_li_key_de1ce8_idx'), models.Index(fields=['stripe_subscription_id'], name='licenses_li_stripe__d51751_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstanceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_registered', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='licenses.license')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['instance_id', 'license'], name='licenses_in_instanc_a33fdf_idx'), models.Index(fields=['license', 'last_seen'], name='licenses_in_license_7fce24_idx')],
            },
        ),
    ]
