# Generated by Django 5.2.15 on 2026-06-07 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField()),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='VaultSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=128)),
                ('encrypted_value', models.TextField()),
                ('iv', models.CharField(max_length=64)),
                ('auth_tag', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_secrets', to='projects.project')),
            ],
            options={
                'ordering': ['key_name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key_name'), name='unique_vault_key_per_project')],
            },
        ),
    ]
