# Generated by Django 5.2.15 on 2026-06-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_org_invites_and_webhook_events'),
        ('projects', '0003_project_organization_projectapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_index=True, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=128)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('entry_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('app_name', models.CharField(max_length=128)),
                ('target_provider', models.CharField(max_length=32)),
                ('requested_by', models.CharField(max_length=128)),
                ('live', models.BooleanField(default=False)),
                ('succeeded', models.BooleanField(default=False)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('provider_service_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_deploy_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_status', models.JSONField(default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, default='')),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_deployment_runs', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_deployment_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
