# Generated by Django 5.2.15 on 2026-06-20 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transfer', '0001_initial'),
        ('organizations', '0003_org_invites_and_webhook_events'),
        ('projects', '0003_project_organization_projectapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mode', models.CharField(default='queue', max_length=16)),
                ('requested_by', models.CharField(default='', max_length=128)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('command', models.JSONField(default=list)),
                ('options', models.JSONField(default=dict)),
                ('step', models.CharField(default='queued', max_length=32)),
                ('step_state', models.JSONField(default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, default='', max_length=260)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_runs', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
