# Generated by Django 5.2.15 on 2026-06-07 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0002_organization_github_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('tier', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('none', 'None')], default='none', max_length=32)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
