# Generated by Django 5.2.15 on 2026-06-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='github_account',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='github_installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
